package org.micoli.micraft.codec.ksp

import com.google.devtools.ksp.getAllSuperTypes
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile

private const val PROTO_ID = "org.micoli.micraft.protocol.ProtoId"
private const val SERVER = "org.micoli.micraft.protocol.ServerMessage"
private const val CLIENT = "org.micoli.micraft.protocol.ClientMessage"

class CodecRegistryProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        CodecRegistryProcessor(environment.codeGenerator, environment.logger)
}

/**
 * Generates `codecServerRegistry()` / `codecClientRegistry()` from every `@ProtoId`-annotated
 * [ServerMessage] / [ClientMessage] subclass, so the wire-id list is never hand-maintained. Fails
 * the build on a missing, duplicate, or non-contiguous `@ProtoId`.
 */
class CodecRegistryProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {
    private var done = false

    private class Entry(
        val id: Int,
        val fqName: String,
        val isObject: Boolean,
        val decl: KSClassDeclaration,
    )

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (done) return emptyList()
        val annotated =
            resolver
                .getSymbolsWithAnnotation(PROTO_ID)
                .filterIsInstance<KSClassDeclaration>()
                .toList()
        if (annotated.isEmpty()) return emptyList()

        val server = mutableListOf<Entry>()
        val client = mutableListOf<Entry>()
        val files = linkedSetOf<KSFile>()

        for (decl in annotated) {
            decl.containingFile?.let(files::add)
            val id = protoId(decl)
            if (id == null) {
                logger.error(
                    "@ProtoId on ${decl.qualifiedName?.asString()} has no readable id", decl)
                continue
            }
            val supers =
                decl
                    .getAllSuperTypes()
                    .mapNotNull { it.declaration.qualifiedName?.asString() }
                    .toSet()
            val bucket =
                when {
                    SERVER in supers -> server
                    CLIENT in supers -> client
                    else -> {
                        logger.error(
                            "@ProtoId on ${decl.qualifiedName?.asString()}: not a ServerMessage/ClientMessage subclass",
                            decl,
                        )
                        continue
                    }
                }
            bucket.add(
                Entry(
                    id, decl.qualifiedName!!.asString(), decl.classKind == ClassKind.OBJECT, decl))
        }

        val serverList = validate("ServerMessage", server) ?: return emptyList()
        val clientList = validate("ClientMessage", client) ?: return emptyList()

        codeGenerator
            .createNewFile(
                Dependencies(aggregating = true, *files.toTypedArray()),
                "org.micoli.micraft.protocol",
                "CodecRegistryGenerated",
            )
            .bufferedWriter()
            .use { w ->
                w.appendLine("// Generated by :codec-processor. Do not edit.")
                w.appendLine("package org.micoli.micraft.protocol")
                w.appendLine()
                w.append(
                    render(
                        "codecServerRegistry",
                        "ServerMessage",
                        "serverEntry",
                        "serverSingleton",
                        serverList))
                w.appendLine()
                w.append(
                    render(
                        "codecClientRegistry",
                        "ClientMessage",
                        "clientEntry",
                        "clientSingleton",
                        clientList))
            }
        done = true
        return emptyList()
    }

    private fun protoId(decl: KSClassDeclaration): Int? {
        val ann =
            decl.annotations.firstOrNull {
                it.annotationType.resolve().declaration.qualifiedName?.asString() == PROTO_ID
            } ?: return null
        val arg =
            ann.arguments.firstOrNull { it.name?.asString() == "id" } ?: ann.arguments.firstOrNull()
        return arg?.value as? Int
    }

    private fun validate(name: String, entries: List<Entry>): List<Entry>? {
        if (entries.isEmpty()) return emptyList()
        var ok = true
        entries
            .groupBy { it.id }
            .filterValues { it.size > 1 }
            .forEach { (id, dups) ->
                ok = false
                logger.error("$name: duplicate @ProtoId($id) on ${dups.map { it.fqName }}")
            }
        val sorted = entries.sortedBy { it.id }
        sorted.forEachIndexed { idx, e ->
            if (e.id != idx) {
                ok = false
                logger.error(
                    "$name: @ProtoId must be contiguous from 0 — expected $idx but ${e.fqName} has ${e.id}",
                    e.decl,
                )
            }
        }
        return if (ok) sorted else null
    }

    private fun render(
        fn: String,
        msgType: String,
        entryFn: String,
        singletonFn: String,
        entries: List<Entry>,
    ): String {
        if (entries.isEmpty())
            return "internal fun $fn(): List<CodecEntry<$msgType>> = emptyList()\n"
        val body =
            entries.joinToString(",\n") { e ->
                if (e.isObject) "    $singletonFn(${e.fqName})" else "    $entryFn<${e.fqName}>()"
            }
        return "internal fun $fn(): List<CodecEntry<$msgType>> = listOf(\n$body,\n)\n"
    }
}
