version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      kotlin-ktor:
        patterns:
          - "org.jetbrains.kotlin*"
          - "io.ktor*"
      koin:
        patterns:
          - "io.insert-koin*"
      other-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "org.jetbrains.kotlin*"
          - "io.ktor*"
          - "io.insert-koin*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directory: "/app/webApp/ts-src"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dev-tooling:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
          - "prettier*"
          - "vitest"
          - "@vitest/*"
          - "vite"
          - "@vitejs/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      other-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "@storybook/*"
          - "storybook"
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
          - "prettier*"
          - "vitest"
          - "@vitest/*"
          - "vite"
          - "@vitejs/*"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/.docker/dev"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/.docker/prod"
    schedule:
      interval: weekly
