blocks:
  AIR: 0
  ACACIA_LOG: 1
  ACACIA_PLANKS: 2
  BEDROCK: 3
  BIRCH_LOG: 4
  BIRCH_PLANKS: 5
  BONE_BLOCK: 6
  BOOKSHELF: 7
  BRICK: 8
  CLAY: 9
  COAL_BLOCK: 10
  COAL_ORE: 11
  COARSE_DIRT: 12
  COBBLESTONE: 13
  CRACKED_STONEBRICK: 14
  CRAFTING_TABLE: 15
  DARK_PRISMARINE: 16
  DIAMOND_BLOCK: 17
  DIAMOND_ORE: 18
  DIRT: 19
  EMERALD_BLOCK: 20
  EMERALD_ORE: 21
  END_STONE: 22
  FLOWER: 23
  FURNACE: 24
  GLASS: 25
  GLOWSTONE: 26
  GOLD_BLOCK: 27
  GOLD_ORE: 28
  GRASS: 29
  GRAVEL: 30
  HAY_BLOCK: 31
  ICE: 32
  IRON_BLOCK: 33
  IRON_ORE: 34
  JUNGLE_LOG: 35
  JUNGLE_PLANKS: 36
  LAPIS_BLOCK: 37
  LAPIS_ORE: 38
  LEGO_ARCH_4X1: 39
  LEGO_ARCH_8X2: 40
  LEGO_BRICK: 41
  LEGO_BRICK_1X2: 42
  LEGO_BRICK_2X1: 43
  LEGO_BRICK_4X1: 44
  LEGO_CORNER: 45
  LEGO_PIECE: 46
  LEGO_PLATE: 47
  LEGO_PLATE_2X2: 48
  LEGO_PLATE_2X4: 49
  LEGO_SLOPE: 50
  LEGO_STEP_BOTTOM: 51
  LEGO_STEP_TOP: 52
  MAGMA: 53
  MELON: 54
  MOSSY_COBBLESTONE: 55
  MOSSY_STONEBRICK: 56
  NETHERRACK: 57
  NETHER_BRICK: 58
  OAK_LEAVES: 59
  OAK_LOG: 60
  OAK_PLANKS: 61
  OBSIDIAN: 62
  PACKED_ICE: 63
  PINE_LEAVES: 64
  PINE_LEAVES_SNOW: 65
  PINE_LOG: 66
  PRISMARINE: 67
  PRISMARINE_BRICKS: 68
  PUMPKIN: 69
  PURPUR_BLOCK: 70
  PURPUR_PILLAR: 71
  QUARTZ_BLOCK: 72
  QUARTZ_ORE: 73
  REDSTONE_BLOCK: 74
  REDSTONE_ORE: 75
  RED_SAND: 76
  SAND: 77
  SANDSTONE: 78
  SAPLING: 79
  SEA_LANTERN: 80
  SEED: 81
  SNOW: 82
  SOUL_SAND: 83
  SPONGE: 84
  SPROUT: 85
  SPRUCE_PLANKS: 86
  STONE: 87
  STONEBRICK: 88
  TNT: 89
  WATER: 90
  WEED: 91
  WOOL_BLACK: 92
  WOOL_BLUE: 93
  WOOL_BROWN: 94
  WOOL_CYAN: 95
  WOOL_GRAY: 96
  WOOL_GREEN: 97
  WOOL_LIGHT_BLUE: 98
  WOOL_LIME: 99
  WOOL_MAGENTA: 100
  WOOL_ORANGE: 101
  WOOL_PINK: 102
  WOOL_PURPLE: 103
  WOOL_RED: 104
  WOOL_SILVER: 105
  WOOL_WHITE: 106
  WOOL_YELLOW: 107
  RAIL_BLOCK_CROSS: 108
  RAIL_BLOCK_CURVE_90: 109
  RAIL_BLOCK_DOUBLE_CURVE_90: 110
  RAIL_BLOCK_SLOPE_45: 111
  RAIL_BLOCK_STRAIGHT: 112
  RAIL_BLOCK_Y_SPLIT_60: 113
  RAIL_BLOCK_Y_SPLIT_90: 114
  RAIL_CROSS: 115
  RAIL_CURVE_90: 116
  RAIL_DOUBLE_CURVE_90: 117
  RAIL_SLOPE_45: 118
  RAIL_STRAIGHT: 119
  RAIL_Y_SPLIT_60: 120
  RAIL_Y_SPLIT_90: 121
  RAIL_CURVE_60: 122
  RAIL_BLOCK_CURVE_60: 123
  RAIL_LEFT_60: 124
  RAIL_RIGHT_60: 125
