# yaml-language-server: $schema=../schemas/classes.schema.json
regen:
  regenIntervalMs: 1000
  default:
    hpFormula: "hpRegenPerSec * dt"
    manaFormula: "manaRegenPerSec * dt"
classes:
  WARRIOR:
    strBonus: 2
    dexBonus: 0
    intelBonus: 0
    wisBonus: 0
    conBonus: 1
    chaBonus: 0
    classResource: RAGE
    hpFormula: "hpRegenPerSec * dt"
    manaFormula: "0"
    rageFormula: "inCombat ? 0.0 : (-con / 20.0 * dt)"
    levels:
      1:
        attacks:
          - attack: slash
            rank: 1
          - attack: heavy_slash
            rank: 1
        spells:
          - tokenRageConsume
          - quickStrike
      3:
        attacks:
          - attack: heavy_slash
            rank: 2
      5:
        attacks:
          - attack: slash
            rank: 2
          - attack: charge
            rank: 1
      7:
        attacks:
          - attack: heavy_slash
            rank: 3
          - attack: charge
            rank: 2
      9:
        attacks:
          - attack: slash
            rank: 3
          - attack: polar_bear_crush
            rank: 1
      11:
        attacks:
          - attack: heavy_slash
            rank: 4
          - attack: charge
            rank: 3
      13:
        attacks:
          - attack: slash
            rank: 4
          - attack: polar_bear_crush
            rank: 2
      15:
        attacks:
          - attack: heavy_slash
            rank: 5
          - attack: polar_bear_crush
            rank: 3
      18:
        attacks:
          - attack: charge
            rank: 4
          - attack: slash
            rank: 5
      20:
        attacks:
          - attack: polar_bear_crush
            rank: 4
          - attack: wolf_pounce
            rank: 5
  MAGE:
    strBonus: 0
    dexBonus: 0
    intelBonus: 2
    wisBonus: 1
    conBonus: 0
    chaBonus: 0
    classResource: MANA
    hpFormula: "hpRegenPerSec * dt * 0.5"
    manaFormula: "manaRegenPerSec * dt * 1.5"
    levels:
      1:
        attacks:
          - attack: fireball
            rank: 1
          - attack: pyre
            rank: 1
        spells:
          - miasme
          - sparkBolt
      2:
        attacks:
          - attack: pyre
            rank: 2
          - attack: freeze
            rank: 1
      3:
        attacks:
          - attack: fireball
            rank: 2
          - attack: pyre
            rank: 3
          - attack: freeze
            rank: 2
        spells:
          - miasme_2
      4:
        attacks:
          - attack: frozen_in_time
            rank: 1
          - attack: freeze
            rank: 3
          - attack: pyre
            rank: 4
      5:
        attacks:
          - attack: fireball
            rank: 3
          - attack: frozen_in_time
            rank: 2
          - attack: freeze
            rank: 4
          - attack: pyre
            rank: 5
        spells:
          - miasme_3
      7:
        attacks:
          - attack: lightning_strike
            rank: 1
          - attack: frozen_in_time
            rank: 3
      9:
        attacks:
          - attack: fireball
            rank: 4
          - attack: lightning_strike
            rank: 2
      11:
        attacks:
          - attack: freeze
            rank: 5
          - attack: frozen_in_time
            rank: 4
      13:
        attacks:
          - attack: ice_claw
            rank: 1
          - attack: lightning_strike
            rank: 3
      15:
        attacks:
          - attack: fireball
            rank: 5
          - attack: frozen_in_time
            rank: 5
      18:
        attacks:
          - attack: ice_claw
            rank: 3
          - attack: lightning_strike
            rank: 4
      20:
        attacks:
          - attack: dragon_fire_breath
            rank: 3
          - attack: lightning_strike
            rank: 5
  RANGER:
    strBonus: 0
    dexBonus: 2
    intelBonus: 0
    wisBonus: 1
    conBonus: 0
    chaBonus: 0
    classResource: MANA
    hpFormula: "hpRegenPerSec * dt"
    manaFormula: "manaRegenPerSec * dt"
    levels:
      1:
        attacks:
          - attack: slash
            rank: 1
          - attack: poison_bite
            rank: 1
        spells:
          - huntersShot
      2:
        attacks:
          - attack: poison_bite
            rank: 2
      3:
        attacks:
          - attack: slash
            rank: 2
      5:
        attacks:
          - attack: poison_bite
            rank: 3
          - attack: wolf_bite
            rank: 1
      7:
        attacks:
          - attack: wolf_bite
            rank: 2
          - attack: slash
            rank: 3
      9:
        attacks:
          - attack: venomous_fang
            rank: 1
          - attack: poison_bite
            rank: 4
      11:
        attacks:
          - attack: wolf_bite
            rank: 3
          - attack: venomous_fang
            rank: 2
      13:
        attacks:
          - attack: slash
            rank: 4
          - attack: venomous_fang
            rank: 3
      15:
        attacks:
          - attack: wolf_bite
            rank: 4
          - attack: poison_bite
            rank: 5
      18:
        attacks:
          - attack: venomous_fang
            rank: 4
          - attack: wolf_bite
            rank: 5
      20:
        attacks:
          - attack: slash
            rank: 5
          - attack: venomous_fang
            rank: 5
  ROGUE:
    strBonus: 0
    dexBonus: 2
    intelBonus: 1
    wisBonus: 0
    conBonus: 0
    chaBonus: 0
    classResource: MANA
    hpFormula: "hpRegenPerSec * dt"
    manaFormula: "manaRegenPerSec * dt"
    levels:
      1:
        attacks:
          - attack: slash
            rank: 1
          - attack: poison_bite
            rank: 1
        spells:
          - swiftStab
      2:
        attacks:
          - attack: slash
            rank: 2
          - attack: poison_bite
            rank: 2
      3:
        attacks:
          - attack: poison_bite
            rank: 3
      5:
        attacks:
          - attack: wolf_pounce
            rank: 1
          - attack: slash
            rank: 3
      7:
        attacks:
          - attack: venomous_fang
            rank: 1
          - attack: poison_bite
            rank: 4
      9:
        attacks:
          - attack: wolf_pounce
            rank: 2
          - attack: slash
            rank: 4
      11:
        attacks:
          - attack: venomous_fang
            rank: 2
          - attack: poison_bite
            rank: 5
      13:
        attacks:
          - attack: wolf_pounce
            rank: 3
          - attack: shadow_claw
            rank: 1
      15:
        attacks:
          - attack: venomous_fang
            rank: 3
          - attack: shadow_claw
            rank: 2
      18:
        attacks:
          - attack: wolf_pounce
            rank: 4
          - attack: shadow_claw
            rank: 3
      20:
        attacks:
          - attack: slash
            rank: 5
          - attack: shadow_claw
            rank: 4
  CLERIC:
    strBonus: 0
    dexBonus: 0
    intelBonus: 0
    wisBonus: 2
    conBonus: 1
    chaBonus: 0
    classResource: MANA
    hpFormula: "hpRegenPerSec * dt * 1.5"
    manaFormula: "manaRegenPerSec * dt"
    levels:
      1:
        attacks:
          - attack: slash
            rank: 1
          - attack: fireball
            rank: 1
        spells:
          - miasme
          - smite
      3:
        attacks:
          - attack: fireball
            rank: 2
        spells:
          - miasme_2
      5:
        spells:
          - miasme_3
      7:
        attacks:
          - attack: fireball
            rank: 3
      9:
        attacks:
          - attack: slash
            rank: 3
          - attack: ice_claw
            rank: 1
      11:
        attacks:
          - attack: fireball
            rank: 4
      13:
        attacks:
          - attack: slash
            rank: 4
          - attack: ice_claw
            rank: 2
      15:
        attacks:
          - attack: fireball
            rank: 5
      18:
        attacks:
          - attack: ice_claw
            rank: 3
          - attack: slash
            rank: 5
      20:
        attacks:
          - attack: ice_claw
            rank: 4
