combat:
  combat_target_cycle: ["Tab"]
  combat_attack: [KeyR]
  npc_interact: [KeyX]
  console_toggle: [KeyH]

movement:
  forward: [KeyW, ArrowUp]
  backward: [KeyS, ArrowDown]
  strafe_right: [KeyD, ArrowRight]
  strafe_left: [KeyA, ArrowLeft]
  rotate_left: [KeyQ]
  rotate_right: [KeyE]
  sneak: [ShiftLeft]
  crawl: [ControlLeft]
  auto_forward: ["KeyW+KeyW", "ArrowUp+ArrowUp"]

flight:
  fly_toggle: ["Space+Space"]
  ascend: [Space]
  descend: [ShiftLeft]
  speed_up: [KeyP]
  speed_down: [KeyO]

ui:
  preferences: ["Cmd+Shift+Comma", "Ctrl+Shift+Comma"]
  preferences_keybindings: ["Cmd+Shift+KeyK", "Ctrl+Shift+KeyK"]
  preferences_debug: ["Cmd+Shift+KeyD", "Ctrl+Shift+KeyD"]
  preferences_graphics: ["Cmd+Shift+KeyG", "Ctrl+Shift+KeyG"]
  console_toggle: [KeyH]
  view_toggle: [KeyF]
  statistics_toggle: [KeyN]
  attack_panel_toggle: [KeyU]
  inventory: [KeyI]
  character: [KeyY]
  undo: ["Ctrl+KeyZ", "Cmd+KeyZ"]
  minimap_zoom_in: [k]
  minimap_zoom_out: [l]
  ingame_map: [m]
  layout_editor: [KeyG]
  dump_stats: [KeyV]
  craft: ["Alt+KeyC"]
  health_bar: [KeyB]
  screenshot: [KeyJ]
  quest_journal: ["Alt+KeyQ"]
  quest_tracking: [KeyT]

building:
  place_rotate: [KeyR]

hotbar:
  slot_1: [Digit1]
  slot_2: [Digit2]
  slot_3: [Digit3]
  slot_4: [Digit4]
  slot_5: [Digit5]
  slot_6: [Digit6]
  slot_7: [Digit7]
  slot_8: [Digit8]
  slot_9: [Digit9]
  slot_10: [Digit0]
  shortcut_page_prev: [":"]
  shortcut_page_next: ["="]
  shortcut_page_1: ["Ctrl+Digit1"]
  shortcut_page_2: ["Ctrl+Digit2"]
  shortcut_page_3: ["Ctrl+Digit3"]
  shortcut_page_4: ["Ctrl+Digit4"]
  shortcut_page_5: ["Ctrl+Digit5"]
  shortcut_page_6: ["Ctrl+Digit6"]
  shortcut_page_7: ["Ctrl+Digit7"]
  shortcut_page_8: ["Ctrl+Digit8"]
  shortcut_page_9: ["Ctrl+Digit9"]
  shortcut_page_10: ["Ctrl+Digit0"]
