namespace = "mc"

[settings.web]
auto_start = true
bind_port = 3120
bind_address = "0.0.0.0"

[daemons.server]
run = "bash -c './gradlew :server:installDist --console=plain && MICRAFT_WEB_DIST=/workspace/app/webApp/build/web /workspace/server/build/install/server/bin/server'"
dir = "/workspace"
ready-port = 8080
retry = true
boot_start = true

[daemons.run-lock]
run = "pitchfork restart server"
dir = "/workspace"
watch = ["run.lock"]
boot_start = true

[daemons.wasm]
run = "./gradlew :app:webApp:copyResourcesToWebDist --continuous --console=plain"
dir = "/workspace"
depends = ["server"]
boot_start = true

[daemons.mc_bindings]
run = "npm run watch:mc_bindings"
dir = "/workspace/app/webApp/ts-src"
env = { MC_OUT_JS="/workspace/app/webApp/build/web/mc_bindings.js"}
depends = ["server"]
boot_start = true

[daemons.css]
run = "npm run watch:css"
dir = "/workspace/app/webApp/ts-src"
env = {MC_OUT_CSS="/workspace/app/webApp/build/web/main.css"}
depends = ["server"]
boot_start = true

[daemons.css-sync]
run = "npm run watch:css:sync"
dir = "/workspace/app/webApp/ts-src"
env = {MC_OUT_CSS="/workspace/app/webApp/build/web/main.css", MC_OUT_MAP_CSS="/workspace/app/webApp/build/web/map.css", MC_OUT_ADMIN_CSS="/workspace/app/webApp/build/web/admin.css"}
depends = ["css"]
boot_start = true

[daemons.map]
run = "npm run watch:map"
dir = "/workspace/app/webApp/ts-src"
env = { MC_OUT_MAP_JS="/workspace/app/webApp/build/web/map.js" }
depends = ["server"]
boot_start = true

[daemons.admin]
run = "npm run watch:admin"
dir = "/workspace/app/webApp/ts-src"
env = { MC_OUT_ADMIN_JS="/workspace/app/webApp/build/web/admin.js" }
depends = ["server"]
boot_start = true
