namespace = "mc"

[settings.web]
auto_start = true
bind_port = 3120
bind_address = "0.0.0.0"

[daemons.server]
run = "bash -c './gradlew :server:installDist :app:webApp:copyStaticToWebDist --console=plain && MICRAFT_WEB_DIST=app/webApp/build/web server/build/install/server/bin/server'"
dir = "."
ready-port = 8080
retry = true
boot_start = true

[daemons.wasm]
run = "./gradlew :app:webApp:copyResourcesToWebDist --continuous --console=plain --no-build-cache"
dir = "."
depends = ["server"]
boot_start = false

[daemons.mc_bindings]
run = "npm run watch:mc_bindings"
dir = "app/webApp/ts-src"
env = { MC_OUT_JS="../build/web/mc_bindings.js"}
depends = ["server"]
boot_start = false

[daemons.css]
run = "npm run watch:css"
dir = "app/webApp/ts-src"
env = {MC_OUT_CSS="../build/web/main.css"}
depends = ["server"]
boot_start = false

[daemons.css-sync]
run = "npm run watch:css:sync"
dir = "app/webApp/ts-src"
env = {MC_OUT_CSS="../build/web/main.css", MC_OUT_MAP_CSS="../build/web/map.css", MC_OUT_ADMIN_CSS="../build/web/admin.css"}
depends = ["css"]
boot_start = false

[daemons.map]
run = "npm run watch:map"
dir = "app/webApp/ts-src"
env = { MC_OUT_MAP_JS="../build/web/map.js" }
depends = ["server"]
boot_start = false

[daemons.admin]
run = "npm run watch:admin"
dir = "app/webApp/ts-src"
env = { MC_OUT_ADMIN_JS="../build/web/admin.js" }
depends = ["server"]
boot_start = false

[daemons.storybook]
run = "npm run storybook dev"
dir = "app/webApp/ts-src"
ready-port = 6006
boot_start = false

[daemons.docs]
run = "bash scripts/docs/mkdocs.sh serve -a 0.0.0.0:8000 -f mkdocs.yml"
dir = "."
env = { DISABLE_MKDOCS_2_WARNING = "true" }
ready-port = 8000
boot_start = false
retry = true

[daemons.e2e-server]
run = "bash -c './gradlew :app:webApp:copyResourcesToWebDist :app:webApp:copyStaticToWebDist --console=plain && (cd app/webApp/ts-src && npm run build) && ./gradlew :server:runE2eServer --console=plain'"
dir = "."
ready-port = 8091
boot_start = false
retry = false
