@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package org.micoli.micraft.protocol

import kotlin.reflect.KClass
import kotlinx.serialization.KSerializer
import kotlinx.serialization.decodeFromByteArray
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToByteArray
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.protobuf.ProtoBuf
import kotlinx.serialization.serializer

@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
annotation class ProtoId(val id: Int)

enum class MessageEncoding {
    PROTOBUF,
    JSON;

    companion object {
        var current: MessageEncoding = PROTOBUF

        fun fromConfigValue(value: String): MessageEncoding =
            when (value.lowercase()) {
                "json" -> JSON
                "protobuf" -> PROTOBUF
                else -> throw IllegalArgumentException("Unknown message encoder: $value")
            }
    }
}

private fun <T> encodeValue(serializer: KSerializer<T>, value: T): ByteArray =
    when (MessageEncoding.current) {
        MessageEncoding.PROTOBUF -> ProtoBuf.encodeToByteArray(serializer, value)
        MessageEncoding.JSON -> Json.encodeToString(serializer, value).encodeToByteArray()
    }

private fun <T> decodeValue(serializer: KSerializer<T>, bytes: ByteArray): T =
    when (MessageEncoding.current) {
        MessageEncoding.PROTOBUF -> ProtoBuf.decodeFromByteArray(serializer, bytes)
        MessageEncoding.JSON -> Json.decodeFromString(serializer, bytes.decodeToString())
    }

internal class CodecEntry<T>(
    val klass: KClass<out Any>,
    val matches: (T) -> Boolean,
    val serializer: KSerializer<T>?,
    val singleton: T? = null,
)

@Suppress("UNCHECKED_CAST")
internal inline fun <reified T : ServerMessage> serverEntry() =
    CodecEntry<ServerMessage>(
        klass = T::class,
        matches = { it is T },
        serializer = serializer<T>() as KSerializer<ServerMessage>,
    )

internal fun serverSingleton(instance: ServerMessage) =
    CodecEntry<ServerMessage>(
        klass = instance::class,
        matches = { it === instance },
        serializer = null,
        singleton = instance,
    )

@Suppress("UNCHECKED_CAST")
internal inline fun <reified T : ClientMessage> clientEntry() =
    CodecEntry<ClientMessage>(
        klass = T::class,
        matches = { it is T },
        serializer = serializer<T>() as KSerializer<ClientMessage>,
    )

internal fun clientSingleton(instance: ClientMessage) =
    CodecEntry<ClientMessage>(
        klass = instance::class,
        matches = { it === instance },
        serializer = null,
        singleton = instance,
    )

private fun <T> encodeWith(registry: List<CodecEntry<T>>, msg: T): ByteArray {
    val idx = registry.indexOfFirst { it.matches(msg) }
    if (idx == -1) throw IllegalArgumentException("Unknown message type: ${msg!!::class}")
    val entry = registry[idx]
    val payload = entry.serializer?.let { encodeValue(it, msg) } ?: ByteArray(0)
    return byteArrayOf(idx.toByte()) + payload
}

private fun <T> decodeWith(registry: List<CodecEntry<T>>, data: ByteArray): T {
    val idx = data[0].toInt()
    val entry =
        registry.getOrNull(idx) ?: throw IllegalArgumentException("Unknown message type id: $idx")
    return entry.serializer?.let { decodeValue(it, data.copyOfRange(1, data.size)) }
        ?: entry.singleton
        ?: throw IllegalStateException("Codec entry $idx has neither serializer nor singleton")
}

object ServerMessageCodec {
    // Generated by :codec-processor from the @ProtoId on each ServerMessage subclass.
    internal val registry: List<CodecEntry<ServerMessage>> = codecServerRegistry()

    fun encode(msg: ServerMessage): ByteArray = encodeWith(registry, msg)

    fun decode(data: ByteArray): ServerMessage = decodeWith(registry, data)
}

object ClientMessageCodec {
    // Generated by :codec-processor from the @ProtoId on each ClientMessage subclass.
    internal val registry: List<CodecEntry<ClientMessage>> = codecClientRegistry()

    fun encode(msg: ClientMessage): ByteArray = encodeWith(registry, msg)

    fun decode(data: ByteArray): ClientMessage = decodeWith(registry, data)
}
