package org.micoli.micraft.tools

import java.io.File
import kotlin.system.exitProcess
import org.micoli.micraft.input.ClientInputAction
import org.micoli.micraft.input.ClientInputEvent

/**
 * Regenerates `app/webApp/ts-src/generated/input/clientEvents.ts` from
 * [org.micoli.micraft.input.ClientInputAction] and [ClientInputEvent]'s payload prefixes — the
 * Kotlin side is the single source of truth for the client-input wire protocol between
 * `keyboard.ts` and `LocalPlayerController.processDiscreteEvents`. Pass `--check` to fail (exit 1)
 * when the committed file is stale instead of rewriting it.
 */
private const val OUT_FILE = "app/webApp/ts-src/generated/input/clientEvents.ts"

private const val HEADER =
    "// GENERATED by :server:generateClientEventTypes — do not edit. Run: make gen-client-events\n" +
        "// Source of truth: core/src/commonMain/kotlin/org/micoli/micraft/input/ClientInputEvent.kt\n"

private fun prefixConstName(prefix: String): String = prefix.removeSuffix(":").uppercase()

fun renderClientEventTypes(): String {
    val actionEntries =
        ClientInputAction.entries.joinToString("\n") { a -> "  ${a.name}: \"${a.wire}\"," }
    val prefixEntries =
        ClientInputEvent.payloadPrefixes.joinToString("\n") { p ->
            "  ${prefixConstName(p)}: \"$p\","
        }
    return HEADER +
        """
        |
        |/** Bare (no-payload) client input events — must match `ClientInputAction` in Kotlin. */
        |export const ClientAction = {
        |$actionEntries
        |} as const;
        |
        |export type ClientAction = (typeof ClientAction)[keyof typeof ClientAction];
        |
        |/**
        | * Wire prefixes for payload-carrying client input events (e.g. `ClientEventPrefix.ATTACK +
        | * attackId + ":" + rank`) — must match the prefixes parsed by `ClientInputEvent.parse` in
        | * Kotlin.
        | */
        |export const ClientEventPrefix = {
        |$prefixEntries
        |} as const;
        |
        |export type ClientEventPrefix = (typeof ClientEventPrefix)[keyof typeof ClientEventPrefix];
        |"""
            .trimMargin()
}

fun main(args: Array<String>) {
    val outFile = File(OUT_FILE)
    val rendered = renderClientEventTypes()
    if ("--check" in args) {
        val current = outFile.takeIf { it.exists() }?.readText()
        if (current == rendered) {
            println("OK. $OUT_FILE is up to date.")
        } else {
            System.err.println("$OUT_FILE is out of date. Run: make gen-client-events")
            exitProcess(1)
        }
        return
    }
    outFile.parentFile.mkdirs()
    outFile.writeText(rendered)
    println("Done. $OUT_FILE written.")
}
