package org.micoli.micraft.tools

import com.charleskorn.kaml.Yaml as Kaml
import com.charleskorn.kaml.YamlList
import com.charleskorn.kaml.YamlMap
import com.charleskorn.kaml.YamlNode
import com.charleskorn.kaml.YamlNull
import com.charleskorn.kaml.YamlScalar
import java.io.File
import kotlin.system.exitProcess
import org.micoli.micraft.game.world.PlayerConstants
import org.micoli.micraft.game.world.WorldConstants

/**
 * Regenerates the reference tables under `docs/reference/_generated/` from the bundled default
 * configuration under `resources/config/` and `resources/blocks/`, and the shared constants in
 * `core`. Mirrors [GenerateCommandsDocs]: pass `--check` to fail (exit 1) when the committed files
 * are stale instead of rewriting them.
 *
 * The site pulls these fragments into hand-written pages through `pymdownx.snippets`, so every "how
 * to configure X" page stays in sync with the code without manual edits.
 */
private const val GENERATED_DIR = "docs/reference/_generated"

private const val HEADER =
    "<!-- GENERATED by :server:generateReferenceDocs — do not edit. Run: make docs -->"

/** File name -> rendered markdown, for every reference fragment. */
fun referenceDocPages(): Map<String, String> = buildMap {
    put("constants.md", constantsPage())
    put("blocks.md", blocksPage())
    put("items.md", simpleMapPage("items", "resources/config/items.yaml", "Item"))
    put("recipes.md", recipesPage())
    put("biomes.md", biomesPage())
    put("classes.md", classesPage())
    put("experience.md", experiencePage())
    put("weather.md", weatherPage())
    put("keybindings.md", keybindingsPage())
    put("config-files.md", configFilesPage())
}

/** Names of fragments whose committed content differs from a fresh render. */
fun staleReferenceDocs(outDir: File = File(GENERATED_DIR)): List<String> =
    referenceDocPages()
        .filter { (name, body) ->
            File(outDir, name).takeIf { it.exists() }?.readText()?.trimEnd() != body.trimEnd()
        }
        .keys
        .toList()

fun main(args: Array<String>) {
    val outDir = File(GENERATED_DIR)
    if ("--check" in args) {
        val stale = staleReferenceDocs(outDir)
        if (stale.isEmpty()) {
            println("OK. ${referenceDocPages().size} reference doc fragments are up to date.")
        } else {
            System.err.println(
                "Reference docs out of date (${stale.joinToString()}). Run: make docs")
            exitProcess(1)
        }
        return
    }
    outDir.mkdirs()
    referenceDocPages().forEach { (name, body) ->
        File(outDir, name).writeText(body.trimEnd() + "\n")
    }
    println("Done. ${referenceDocPages().size} reference doc fragments written to $GENERATED_DIR/")
}

// --- YAML helpers -----------------------------------------------------------------------

private fun yaml(path: String): YamlNode = Kaml.default.parseToYamlNode(File(path).readText())

private fun yamlOrNull(path: String): YamlNode? = runCatching { yaml(path) }.getOrNull()

private operator fun YamlNode.get(key: String): YamlNode? =
    (this as? YamlMap)?.entries?.entries?.firstOrNull { it.key.content == key }?.value

private val YamlNode.scalar: String?
    get() = (this as? YamlScalar)?.content

private val YamlNode.items: List<YamlNode>
    get() = (this as? YamlList)?.items ?: emptyList()

private val YamlNode.mapEntries: List<Pair<String, YamlNode>>
    get() = (this as? YamlMap)?.entries?.entries?.map { it.key.content to it.value } ?: emptyList()

private fun YamlNode?.str(key: String): String =
    this?.get(key)?.let { if (it is YamlNull) "—" else it.scalar ?: it.render() } ?: "—"

private fun YamlNode.render(): String =
    when (this) {
        is YamlScalar -> content
        is YamlList -> items.joinToString(", ") { it.render() }
        is YamlNull -> "—"
        else -> "…"
    }

private fun md(title: String, intro: String, table: String): String = buildString {
    appendLine(HEADER)
    appendLine()
    appendLine("### $title")
    appendLine()
    if (intro.isNotBlank()) {
        appendLine(intro)
        appendLine()
    }
    append(table)
}

private fun table(headers: List<String>, rows: List<List<String>>): String = buildString {
    appendLine("| " + headers.joinToString(" | ") + " |")
    appendLine("|" + headers.joinToString("") { "---|" })
    rows.forEach { r -> appendLine("| " + r.joinToString(" | ") { it.replace("|", "\\|") } + " |") }
}

// --- pages -----------------------------------------------------------------------------

private fun constantsPage(): String {
    fun rows(obj: Any) =
        obj.javaClass.declaredFields
            .filter { !it.isSynthetic && it.name != "INSTANCE" }
            .sortedBy { it.name }
            .map {
                it.isAccessible = true
                listOf("`${it.name}`", "`${it.get(obj)}`")
            }

    return md(
        "World constants",
        "Shared between client and server (`core`). Values marked `var` can be overridden " +
            "at startup by `data/config/server.yaml`.",
        table(listOf("Constant", "Default"), rows(WorldConstants)),
    ) +
        "\n" +
        md(
            "Player constants",
            "Stances and movement (`core`).",
            table(listOf("Constant", "Default"), rows(PlayerConstants)))
}

private fun blocksPage(): String {
    val dir = File("resources/blocks")
    val rows =
        dir.listFiles { f -> f.isDirectory }
            .orEmpty()
            .sortedBy { it.name }
            .mapNotNull { d ->
                val f = File(d, "${d.name}.yaml").takeIf { it.exists() } ?: return@mapNotNull null
                val n = yamlOrNull(f.path) ?: return@mapNotNull null
                val drops =
                    n["drops"]?.items?.joinToString(", ") {
                        "${it.str("item")}×${it.str("minCount")}–${it.str("maxCount")} @${it.str("dropRate")}%"
                    } ?: "—"
                listOf(
                    "`${d.name}`",
                    n.str("hardness"),
                    n.str("solid"),
                    n.str("liquid"),
                    n.str("replaceable"),
                    n.str("vegetationHost"),
                    drops,
                )
            }
    return md(
        "Blocks",
        "Sourced from `resources/blocks/<name>/<name>.yaml`, overridable per-block under " +
            "`data/resources/blocks/`. `hardness: -1` = unbreakable.",
        table(
            listOf("Block", "Hardness", "Solid", "Liquid", "Replaceable", "Veg. host", "Drops"),
            rows),
    )
}

private fun simpleMapPage(id: String, path: String, noun: String): String {
    val n = yaml(path)
    val keys = n.mapEntries.flatMap { (_, v) -> v.mapEntries.map { it.first } }.distinct()
    val rows =
        n.mapEntries.map { (name, v) ->
            listOf("`$name`") + keys.map { k -> v[k]?.render() ?: "—" }
        }
    return md(
        "${noun}s",
        "Defined in `data/config/$id.yaml` (bundled defaults in `resources/config/$id.yaml`).",
        table(listOf(noun) + keys, rows),
    )
}

private fun recipesPage(): String {
    val n = yaml("resources/config/recipes.yaml")
    val rows =
        n.mapEntries.map { (id, r) ->
            listOf(
                "`$id`",
                r["items"]?.render() ?: "—",
                "${r.str("giveAmount")}× ${r.str("giveType")} `${r.str("giveId")}`",
            )
        }
    return md(
        "Recipes",
        "Defined in `data/config/recipes.yaml`. `items` are `TYPE*count` inputs; unlock a " +
            "recipe with `/learnrecipe`, craft with `/craft` or `/docraft`.",
        table(listOf("Recipe", "Inputs", "Output"), rows),
    )
}

private fun biomesPage(): String {
    val n = yaml("resources/config/biomes.yaml")
    val rows =
        n["biomes"]?.items.orEmpty().map { b ->
            val zone = b["zones"]?.items?.firstOrNull()
            listOf(
                "`${b.str("id")}`",
                b.str("surface"),
                b.str("subsurface"),
                "${zone.str("altitudeMin")}–${zone.str("altitudeMax")}",
                "${zone.str("moistureMin")}–${zone.str("moistureMax")}",
                b.str("maxNpcs"),
                b["vegetation"]?.items?.joinToString(", ") {
                    "${it.str("type")} @${it.str("density")}"
                } ?: "—",
            )
        }
    return md(
        "Biomes",
        "Defined in `data/config/biomes.yaml`. Distributed via Voronoi zones " +
            "(`voronoiCellSize: ${n.str("voronoiCellSize")}`, blend `${n.str("voronoiBlendRadius")}`) " +
            "keyed on moisture × altitude.",
        table(
            listOf(
                "Biome", "Surface", "Subsurface", "Altitude", "Moisture", "Max NPCs", "Vegetation"),
            rows),
    )
}

private fun classesPage(): String {
    val n = yaml("resources/config/classes.yaml")
    val rows =
        n["classes"]?.mapEntries.orEmpty().map { (name, c) ->
            listOf(
                "`$name`",
                c.str("classResource"),
                c.str("strBonus"),
                c.str("dexBonus"),
                c.str("intelBonus"),
                c.str("wisBonus"),
                c.str("conBonus"),
                c.str("chaBonus"),
            )
        }
    return md(
        "RPG classes",
        "Defined in `data/config/classes.yaml`. Base stats are added to the class bonus " +
            "shown here; HP/mana/rage formulas and regen are in the same file.",
        table(listOf("Class", "Resource", "STR", "DEX", "INT", "WIS", "CON", "CHA"), rows),
    )
}

private fun experiencePage(): String {
    val n = yaml("resources/config/experience.yaml")
    val thresholds = n["progression"]?.get("thresholds")?.items.orEmpty()
    val rows = thresholds.mapIndexed { i, t -> listOf("L${i + 1} → L${i + 2}", "`${t.scalar}`") }
    val src = n["sources"]
    return md(
        "Experience & progression",
        "Defined in `data/config/experience.yaml`. XP awarded per kill: " +
            "common `${src.str("commonPerLevel")}`/level, elite `${src.str("elitePerLevel")}`/level, " +
            "boss `${src.str("bossPerLevel")}`/level. Group bonus " +
            "`${n["group"].str("bonusPerMember")}` per extra member.",
        table(listOf("Level up", "Cumulative XP"), rows),
    )
}

private fun weatherPage(): String {
    val n = yaml("resources/config/weather.yaml")
    val rows =
        n["weatherTypes"]?.items.orEmpty().map { w ->
            listOf(
                "`${w.str("type")}`",
                w["biomes"]?.render() ?: "—",
                w.str("spawnRatePerBiomeTick"),
                "${w.str("minDurationTicks")}–${w.str("maxDurationTicks")}",
                "${w.str("minRadius")}–${w.str("maxRadius")}",
                w.str("driftSpeed"),
            )
        }
    return md(
        "Weather zones",
        "Defined in `data/config/weather.yaml`. Zones spawn per biome tick, drift, and " +
            "expire. Force one with `/weather`, inspect active zones with `/weather-forecast`.",
        table(
            listOf("Type", "Biomes", "Spawn rate/tick", "Duration (ticks)", "Radius", "Drift"),
            rows),
    )
}

private fun keybindingsPage(): String {
    val n = yaml("resources/config/keybindings.yaml")
    val rows =
        n.mapEntries.flatMap { (group, actions) ->
            actions.mapEntries.map { (action, keys) ->
                listOf("`$group`", "`$action`", keys.render())
            }
        }
    return md(
        "Default keybindings",
        "Defined in `data/config/keybindings.yaml` (bundled defaults in `resources/config/`). " +
            "Players override their own bindings in-game; any slash command can be bound too.",
        table(listOf("Group", "Action", "Default keys"), rows),
    )
}

private fun configFilesPage(): String {
    val schemas =
        File("server/src/main/resources/schemas")
            .list()
            .orEmpty()
            .map { it.removeSuffix(".schema.json") }
            .toSet()
    val rows =
        File("resources/config")
            .listFiles { f -> f.extension == "yaml" }
            .orEmpty()
            .sortedBy { it.name }
            .map { f ->
                val id = f.nameWithoutExtension
                listOf(
                    "`data/config/${f.name}`",
                    if (id in schemas) "`$id.schema.json`" else "—",
                    "`resources/config/${f.name}`",
                )
            }
    return md(
        "Configuration files",
        "Every file is optional: on first run the server writes a fully-commented template " +
            "into `data/config/`, merging any bundled default. Reload most of them at runtime " +
            "with `/reload` or `/config:reload`.",
        table(listOf("Override file", "JSON Schema", "Bundled default"), rows),
    )
}
