package org.micoli.micraft.tools

import java.io.File
import kotlin.system.exitProcess
import org.micoli.micraft.input.MovementAction

/**
 * Regenerates `app/webApp/ts-src/generated/input/movementActions.ts` from
 * [org.micoli.micraft.input.MovementAction] — the Kotlin side is the single source of truth for the
 * continuous movement actions polled via `jsIsActionDown`/`mc.isActionDown`. Pass `--check` to fail
 * (exit 1) when the committed file is stale instead of rewriting it.
 */
private const val OUT_FILE = "app/webApp/ts-src/generated/input/movementActions.ts"

private const val HEADER =
    "// GENERATED by :server:generateMovementActionTypes — do not edit. Run: make gen-movement-actions\n" +
        "// Source of truth: core/src/commonMain/kotlin/org/micoli/micraft/input/MovementAction.kt\n"

fun renderMovementActionTypes(): String {
    val actionEntries =
        MovementAction.entries.joinToString("\n") { a -> "  ${a.name}: \"${a.wire}\"," }
    return HEADER +
        """
        |
        |/**
        | * Continuous movement actions polled via `mc.isActionDown(action)` — must match
        | * `MovementAction` in Kotlin.
        | */
        |export const MovementAction = {
        |$actionEntries
        |} as const;
        |
        |export type MovementAction = (typeof MovementAction)[keyof typeof MovementAction];
        |"""
            .trimMargin()
}

fun main(args: Array<String>) {
    val outFile = File(OUT_FILE)
    val rendered = renderMovementActionTypes()
    if ("--check" in args) {
        val current = outFile.takeIf { it.exists() }?.readText()
        if (current == rendered) {
            println("OK. $OUT_FILE is up to date.")
        } else {
            System.err.println("$OUT_FILE is out of date. Run: make gen-movement-actions")
            exitProcess(1)
        }
        return
    }
    outFile.parentFile.mkdirs()
    outFile.writeText(rendered)
    println("Done. $OUT_FILE written.")
}
