// Auto-generated by scripts/gen-plugins-index.mjs — do not edit manually.
import { registerCompass } from './compass/client/index';
import { registerGoto } from './goto/client/index';
import { registerKick } from './kick/client/index';
import { registerNpc } from './npc/client/index';
import { registerSummon } from './summon/client/index';
import { registerTeleport } from './teleport/client/index';
import { registerWho } from './who/client/index';
import { registerYield } from './yield/client/index';

export function registerAllPlugins(): void {
  registerCompass();
  registerGoto();
  registerKick();
  registerNpc();
  registerSummon();
  registerTeleport();
  registerWho();
  registerYield();
}
