damageType: PHYSICAL
enabled: true
levels:
  1:
    power: 5
    weaponDice: 1d6
    cooldownMs: 1300
    statusEffect: Paralyzed
  2:
    power: 8
    weaponDice: 1d8
    cooldownMs: 1200
    statusEffect: Paralyzed
