# yaml-language-server: $schema=../../schemas/skill-attack.schema.json
damageType: MAGIC
enabled: true
levels:
  1:
    power: 5
    weaponDice: 1d6
    cooldownMs: 4000
    manaCost: 30
    statusEffect: FrozenInTime
  2:
    power: 8
    weaponDice: 2d6
    cooldownMs: 3800
    manaCost: 45
    statusEffect: FrozenInTime
  3:
    power: 12
    weaponDice: 3d6
    cooldownMs: 3500
    manaCost: 62
    statusEffect: FrozenInTime
  4:
    power: 16
    weaponDice: 4d6
    cooldownMs: 3200
    manaCost: 80
    statusEffect: FrozenInTime
  5:
    power: 21
    weaponDice: 5d6
    cooldownMs: 3000
    manaCost: 100
    statusEffect: FrozenInTime
