damageType: PHYSICAL
enabled: true
levels:
  1:
    power: 10
    weaponDice: 2d8
    cooldownMs: 1500
    rageCost: 20
  2:
    power: 15
    weaponDice: 3d8
    cooldownMs: 1400
    rageCost: 25
  3:
    power: 15
    weaponDice: 3d8
    cooldownMs: 1400
    rageCost: 25
  4:
    power: 20
    weaponDice: 4d8
    cooldownMs: 1300
    rageCost: 30
  5:
    power: 26
    weaponDice: 5d8
    cooldownMs: 1200
    rageCost: 35
    statusEffect: Stunned
