damageType: POISON
enabled: true
levels:
  1:
    power: 4
    weaponDice: 1d6
    cooldownMs: 1000
  2:
    power: 7
    weaponDice: 2d6
    cooldownMs: 950
  3:
    power: 10
    weaponDice: 2d8
    cooldownMs: 900
    statusEffect: Poisoned
  4:
    power: 13
    weaponDice: 3d6
    cooldownMs: 850
    statusEffect: Poisoned
  5:
    power: 17
    weaponDice: 3d8
    cooldownMs: 800
    statusEffect: Poisoned
