package org.micoli.micraft.tools

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class GenerateReferenceDocsTest {

    @Test
    fun `every fragment renders a non-empty markdown table with the generated header`() {
        val pages = referenceDocPages()
        assertTrue(pages.isNotEmpty())
        pages.forEach { (name, body) ->
            assertTrue(body.contains("GENERATED by :server:generateReferenceDocs"), "$name header")
            assertTrue(body.contains("|---"), "$name has a table")
        }
    }

    @Test
    fun `constants fragment reflects the shared core objects`() {
        val body = referenceDocPages().getValue("constants.md")
        assertTrue(body.contains("`CHUNK_SIZE`"))
        assertTrue(body.contains("`HEIGHT_STANDING`"))
    }

    @Test
    fun `every fragment has a committed file under docs`() {
        // Content drift is verified by :server:checkReferenceDocs (its own JVM):
        // the mutable WorldConstants / PlayerConstants globals make an in-suite
        // content comparison unreliable when other tests have run first.
        val missing =
            referenceDocPages().keys.filterNot { File("docs/reference/_generated/$it").exists() }
        assertEquals(emptyList(), missing, "Run: make docs")
    }

    @Test
    fun `check mode reads the same directory the generator writes`() {
        val tmp =
            File.createTempFile("refdocs", "").apply {
                delete()
                mkdirs()
            }
        referenceDocPages().forEach { (n, b) -> File(tmp, n).writeText(b.trimEnd() + "\n") }
        assertEquals(emptyList(), staleReferenceDocs(tmp))
        tmp.deleteRecursively()
    }
}
