package org.micoli.micraft.tools

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.micoli.micraft.input.MovementAction

class GenerateMovementActionTypesTest {

    @Test
    fun `renders the generated header and every movement action`() {
        val rendered = renderMovementActionTypes()
        assertTrue(rendered.contains("GENERATED by :server:generateMovementActionTypes"))
        MovementAction.entries.forEach { a ->
            assertTrue(rendered.contains("${a.name}: \"${a.wire}\","), "missing ${a.name}")
        }
    }

    @Test
    fun `committed file matches the generator output`() {
        val committed = File("app/webApp/ts-src/generated/input/movementActions.ts")
        assertTrue(committed.exists(), "Run: make gen-movement-actions")
        assertEquals(renderMovementActionTypes(), committed.readText())
    }
}
