package org.micoli.micraft.tools

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class GenerateReferenceDocsTest {

    @Test
    fun `every fragment renders a non-empty markdown table with the generated header`() {
        val pages = referenceDocPages()
        assertTrue(pages.isNotEmpty())
        pages.forEach { (name, body) ->
            assertTrue(body.contains("GENERATED by :server:generateReferenceDocs"), "$name header")
            assertTrue(body.contains("|---"), "$name has a table")
        }
    }

    @Test
    fun `constants fragment reflects the shared core objects`() {
        val body = referenceDocPages().getValue("constants.md")
        assertTrue(body.contains("`CHUNK_SIZE`"))
        assertTrue(body.contains("`HEIGHT_STANDING`"))
    }

    @Test
    fun `committed fragments under docs are up to date with config and constants`() {
        val stale = staleReferenceDocs()
        assertEquals(
            emptyList(), stale, "Run: make docs (or ./gradlew :server:generateReferenceDocs)")
    }

    @Test
    fun `check mode reads the same directory the generator writes`() {
        val tmp =
            File.createTempFile("refdocs", "").apply {
                delete()
                mkdirs()
            }
        referenceDocPages().forEach { (n, b) -> File(tmp, n).writeText(b.trimEnd() + "\n") }
        assertEquals(emptyList(), staleReferenceDocs(tmp))
        tmp.deleteRecursively()
    }
}
