type: PROTECTION
enabled: true
ranks:
  1:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 10
    rageCost: 0
    maxHpBonus: 10
    hpRegenMultBonus: 0.5
  2:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 15
    rageCost: 0
    maxHpBonus: 20
    hpRegenMultBonus: 0.5
  3:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 20
    rageCost: 0
    maxHpBonus: 35
    hpRegenMultBonus: 0.5
  4:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 25
    rageCost: 0
    maxHpBonus: 50
    hpRegenMultBonus: 0.5
  5:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 30
    rageCost: 0
    maxHpBonus: 70
    hpRegenMultBonus: 0.5
