type: PROTECTION
enabled: true
ranks:
  1:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 10
    rageCost: 0
    acBonus: 4
  2:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 15
    rageCost: 0
    acBonus: 5
  3:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 20
    rageCost: 0
    acBonus: 6
  4:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 25
    rageCost: 0
    acBonus: 7
  5:
    durationSec: 60.0
    cooldownMs: 90000
    manaCost: 30
    rageCost: 0
    acBonus: 8
